#!/bin/sh

set -e


PACKAGE=beanstalkd
DEFAULTSFILE=/etc/default/$PACKAGE

#DEBHELPER#

case "$1" in
    configure)

        # Create beanstalkd system user
        getent passwd beanstalkd > /dev/null || \
            adduser --quiet --system --home /var/lib/beanstalkd  --no-create-home \
            --gecos 'Beanstalk Server' --group beanstalkd

        ;;

    failed-upgrade|abort-upgrade|abort-remove|abort-deconfigure|in-favour|removing)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 1;
        ;;
esac

# create default file if it doesn't exist already
test -e $DEFAULTSFILE || \
cat >$DEFAULTSFILE <<EOF
## Defaults for the beanstalkd init script, /etc/init.d/beanstalkd on
## Debian systems. Append ``-b /var/lib/beanstalkd'' for persistent
## storage. See beanstalkd(1) for details.
DAEMON_OPTS="-d -f beanstalkd"
EOF

# Automatically added by dh_installinit
if [ -x "/etc/init.d/beanstalkd" ]; then
	update-rc.d beanstalkd start 20 2 3 4 5 . stop 20 1 . >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d beanstalkd start || exit $?
	else
		/etc/init.d/beanstalkd start || exit $?
	fi
fi
# End automatically added section


exit 0
