#!/bin/sh
# vim: ts=4:et:sts=4
# $Id: beanstalkd.postrm 89 2009-01-03 16:34:01Z robert $

set -e

#DEBHELPER#

PACKAGE=beanstalkd
DEFAULTSFILE=/etc/default/$PACKAGE


cleanupUcf() 
{
    which ucf >/dev/null && HAS_UCF=yes || HAS_UCF=no
    which ucfr >/dev/null && HAS_UCFR=yes || HAS_UCFR=no
    # we mimic dpkg as closely as possible, so we remove configuration
    # files with dpkg backup extensions too:
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist .dpkg-tmp '';  do
        rm -f "${DEFAULTSFILE}${ext}"
    done
    [ "$HAS_UCF"  != "yes"  ] || ucf  --purge "$DEFAULTSFILE"
    [ "$HAS_UCFR" != "yes" ]  || ucfr --purge "$PACKAGE" "$DEFAULTSFILE"
}

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d beanstalkd remove >/dev/null || exit $?
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
 

case "$1" in
   failed-install|abort-install|abort-upgrade|failed-upgrade)
        exit 0
    ;;

    remove)
        if [ $(find /var/lib/beanstalkd -type f | wc -l) -eq 0 ]; then
            rmdir /var/lib/beanstalkd
        else
            echo "/var/lib/beanstalkd is not empty; not deleting"
        exit 0
    ;;
    purge)

        rm -rf /var/lib/beanstalkd/
        [ ! -d /etc/beanstalkd ] || rmdir  --ignore-fail-on-non-empty /etc/beanstalkd || true
        cleanupUcf

        # remove user, group and home directory beanstalkd
        deluser --remove-home beanstalkd >/dev/null 2>&1 || true

        exit 0
    ;;
    upgrade|disappear)
        exit 0
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
