#!/bin/sh

set -e


PACKAGE=beanstalkd
DEFAULTSFILE=/etc/default/$PACKAGE

case "$1" in
    configure)

        # Create beanstalkd system user
        getent passwd beanstalkd > /dev/null || \
            adduser --quiet --system --home /var/lib/beanstalkd  --no-create-home \
            --gecos 'Beanstalk Server' --group beanstalkd

        ;;

    failed-upgrade|abort-upgrade|abort-remove|abort-deconfigure|in-favour|removing)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 1;
        ;;
esac

# create default file if it doesn't exist already
test -e $DEFAULTSFILE || \
cat >$DEFAULTSFILE <<EOF
## Defaults for the beanstalkd init script, /etc/init.d/beanstalkd on
## Debian systems. Append ``-b /var/lib/beanstalkd'' for persistent
## storage.
DAEMON_OPTS=""

## Uncomment to enable startup during boot.
#START=yes
EOF

chown beanstalkd:beanstalkd /var/lib/beanstalkd/

#DEBHELPER#

exit 0
